#!/usr/bin/env python3
"""Export public, six-tab ranking workbooks after ``build_dashboard.py``.

Run from the repository root:

    python export_public_rankings.py

By default the workbooks are written to ``output/public_rankings``.  The
script consumes only files generated by ``python build_dashboard.py``; it
does not rerun or recalculate any ranking system.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import pandas as pd
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.table import Table, TableStyleInfo


ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT / "code"))

from jpar_pipeline import make_event_time_records_df, make_qualified_events_df  # noqa: E402


CALCULATION_CSV = ROOT / "data/data_jpar_v2/source_of_truth_calculation_df.csv"
JPAR_RESULTS_CSV = ROOT / "data/data_jpar_v2/source_of_truth_jpar_results.csv"
EXTERNAL_LEADERBOARD_CSV = ROOT / "data/colleague_systems/final_leaderboard.csv"
EXTERNAL_HISTORY_CSV = ROOT / "data/colleague_systems/state_history.csv"


@dataclass(frozen=True)
class RankingMethod:
    key: str
    label: str
    sheet_label: str
    filename: str
    higher_is_better: bool


METHODS = (
    RankingMethod("jpar", "JPAR", "JPAR", "jpar_rankings.xlsx", False),
    RankingMethod(
        "external_logtime",
        "Log-Time Volatility Mean",
        "Log-Time Mean",
        "logtime_volatility_mean_rankings.xlsx",
        True,
    ),
    RankingMethod(
        "external_logtime_conservative",
        "Log-Time Volatility Conservative",
        "Log-Time Conservative",
        "logtime_volatility_conservative_rankings.xlsx",
        True,
    ),
)

HEADER_FILL = PatternFill("solid", fgColor="4F81BD")
HEADER_FONT = Font(color="FFFFFF", bold=True)
TITLE_FILL = PatternFill("solid", fgColor="D9EAF7")
THIN_BLUE = Side(style="thin", color="9EBDD7")


def member_key(value: object) -> str:
    """Normalize IDs that pandas may read as numeric strings ending in .0."""
    if pd.isna(value):
        return ""
    text = str(value).strip()
    return text[:-2] if re.fullmatch(r"\d+\.0", text) else text


def event_key(value: object) -> str:
    if pd.isna(value):
        return ""
    text = str(value).strip()
    return text[:-2] if re.fullmatch(r"\d+\.0", text) else text


def ranked_frame(
    names: pd.DataFrame,
    score_col: str,
    event_col: str,
    higher_is_better: bool,
) -> pd.DataFrame:
    frame = names[["member_key", "full_name", score_col, event_col]].copy()
    frame = frame.rename(columns={score_col: "Rating", event_col: "# Events", "full_name": "Name"})
    frame["Rating"] = pd.to_numeric(frame["Rating"], errors="coerce")
    frame["# Events"] = pd.to_numeric(frame["# Events"], errors="coerce").fillna(0).astype(int)
    frame = frame.dropna(subset=["Rating"])
    frame = frame[frame["Name"].fillna("").astype(str).str.strip().ne("")]
    frame = frame.sort_values(
        ["Rating", "Name", "member_key"],
        ascending=[not higher_is_better, True, True],
        kind="stable",
    ).reset_index(drop=True)
    # Match Excel RANK.EQ semantics: tied values receive the same rank.
    frame.insert(0, "Rank", frame["Rating"].rank(method="min", ascending=not higher_is_better).astype(int))
    return frame[["Rank", "Rating", "Name", "# Events", "member_key"]]


def participant_updates(history: pd.DataFrame, score_col: str) -> pd.DataFrame:
    """Keep only rows where a person's event count increases."""
    h = history.copy()
    h["event_date"] = pd.to_datetime(h["event_date"], errors="coerce")
    h["event_id"] = h["event_id"].map(event_key)
    h["member_key"] = h["member_key"].map(member_key)
    h["events"] = pd.to_numeric(h["events"], errors="coerce").fillna(0).astype(int)
    h[score_col] = pd.to_numeric(h[score_col], errors="coerce")
    h = h.sort_values(["member_key", "event_date", "event_id"], kind="stable")
    previous = h.groupby("member_key")["events"].shift(fill_value=0)
    return h[h["events"].gt(previous)].copy()


def monthly_frames(
    updates: pd.DataFrame,
    score_col: str,
    names: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    d = updates.dropna(subset=["event_date", score_col]).copy()
    d["Month"] = d["event_date"].dt.to_period("M")
    if d.empty:
        empty = pd.DataFrame(columns=["Month", "Name", "Rating", "Event #"])
        return empty, pd.DataFrame(columns=["Name"])

    monthly_score = (
        d.sort_values(["member_key", "event_date", "event_id"], kind="stable")
        .groupby(["member_key", "Month"], as_index=False)[score_col]
        .last()
    )
    monthly_events = (
        d.groupby(["member_key", "Month"], as_index=False)["event_id"]
        .nunique()
        .rename(columns={"event_id": "Event #"})
    )
    months = pd.period_range(d["Month"].min(), d["Month"].max(), freq="M")
    people = names[["member_key", "full_name"]].drop_duplicates("member_key")
    grid = people.assign(_join=1).merge(pd.DataFrame({"Month": months, "_join": 1}), on="_join").drop(columns="_join")
    grid = grid.merge(monthly_score, on=["member_key", "Month"], how="left")
    grid = grid.merge(monthly_events, on=["member_key", "Month"], how="left")
    grid = grid.sort_values(["member_key", "Month"], kind="stable")
    grid[score_col] = grid.groupby("member_key")[score_col].ffill()
    grid["Event #"] = grid["Event #"].fillna(0).astype(int)
    grid["Month"] = grid["Month"].astype(str)
    grid = grid.rename(columns={"full_name": "Name", score_col: "Rating"})

    monthly_list = grid[["Month", "Name", "Rating", "Event #"]].sort_values(["Name", "Month"], kind="stable")
    # The public workbook identifies people by display name.  If two member IDs
    # share a name, retain the latest value just as the public name-only grid does.
    monthly_grid = monthly_list.pivot_table(
        index="Name", columns="Month", values="Rating", aggfunc="last", sort=False
    ).reset_index()
    return monthly_list.reset_index(drop=True), monthly_grid


def jpar_data(results: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, str, str]:
    d = results.copy()
    d["member_key"] = d["resolved_member_id"].map(member_key)
    d["full_name"] = d["member_full_name"].fillna(d["full_name"])
    d["event_date"] = pd.to_datetime(d["event_date"], errors="coerce")
    d["event_id"] = d["event_id"].map(event_key)
    d["jpar"] = pd.to_numeric(d["jpar_out"], errors="coerce")
    d = d[d["member_key"].ne("")].sort_values(["member_key", "event_date", "event_id"], kind="stable")
    d["events"] = d.groupby("member_key").cumcount() + 1
    latest = d.groupby("member_key", as_index=False).tail(1)
    return latest, d, "jpar", "events"


def external_data(
    leaderboard: pd.DataFrame,
    history: pd.DataFrame,
    score_col: str,
) -> tuple[pd.DataFrame, pd.DataFrame, str, str]:
    latest = leaderboard.copy()
    latest["member_key"] = latest["member_key"].map(member_key)
    updates = participant_updates(history, score_col)
    return latest, updates, score_col, "external_events"


def excel_value(value: object) -> object:
    if pd.isna(value):
        return None
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if isinstance(value, pd.Timestamp):
        return value.to_pydatetime()
    return value


def add_dataframe(ws, frame: pd.DataFrame, table_name: str | None = None) -> None:
    ws.append([str(c) for c in frame.columns])
    for row in frame.itertuples(index=False, name=None):
        ws.append([excel_value(value) for value in row])
    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions
    if table_name and ws.max_row > 1:
        table = Table(displayName=table_name, ref=ws.dimensions)
        table.tableStyleInfo = TableStyleInfo(
            name="TableStyleMedium2", showFirstColumn=False, showLastColumn=False,
            showRowStripes=True, showColumnStripes=False,
        )
        ws.add_table(table)


def style_sheet(ws) -> None:
    ws.sheet_view.showGridLines = False
    ws.row_dimensions[1].height = 22
    for column_cells in ws.iter_cols():
        letter = get_column_letter(column_cells[0].column)
        width = max((len(str(cell.value)) for cell in column_cells[:250] if cell.value is not None), default=8) + 2
        ws.column_dimensions[letter].width = min(max(width, 10), 42)
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row):
        for cell in row:
            cell.alignment = Alignment(vertical="top")


def add_qualified_events(ws, qualified: pd.DataFrame, method: RankingMethod) -> None:
    ws.append([f"{method.label} is calculated from the qualifying events listed below."])
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=len(qualified.columns))
    ws["A1"].fill = TITLE_FILL
    ws["A1"].font = Font(bold=True, color="1F4E78")
    ws["A1"].alignment = Alignment(wrap_text=True)
    ws.append(list(qualified.columns))
    for row in qualified.itertuples(index=False, name=None):
        ws.append([excel_value(value) for value in row])
    for cell in ws[2]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
    ws.freeze_panes = "A3"
    ws.auto_filter.ref = f"A2:{get_column_letter(ws.max_column)}{ws.max_row}"


def add_event_times(ws, event_times: pd.DataFrame) -> None:
    display = event_times.drop(columns=["Member ID"], errors="ignore").rename(columns={"Name": "Full Name"})
    add_dataframe(ws, display)
    ws.freeze_panes = "B2"
    for column in range(2, ws.max_column + 1):
        for cell in ws.iter_cols(min_col=column, max_col=column, min_row=2):
            for item in cell:
                item.alignment = Alignment(horizontal="center")


def build_workbook(
    method: RankingMethod,
    ranked: pd.DataFrame,
    monthly_list: pd.DataFrame,
    monthly_grid: pd.DataFrame,
    qualified: pd.DataFrame,
    event_times: pd.DataFrame,
    output_path: Path,
) -> None:
    wb = Workbook()
    wb.remove(wb.active)

    ws = wb.create_sheet("Qualified Events")
    add_qualified_events(ws, qualified, method)

    ws = wb.create_sheet("Event Time Records")
    add_event_times(ws, event_times)

    score_header = method.label
    by_name = ranked.sort_values(["Name", "Rank"], kind="stable").drop(columns="member_key")
    by_name = by_name.rename(columns={"Rating": score_header})
    ws = wb.create_sheet(f"{method.sheet_label} by Name")
    add_dataframe(ws, by_name, "RankingByName")

    by_rank = ranked.drop(columns="member_key").rename(columns={"Rating": score_header})
    ws = wb.create_sheet(f"{method.sheet_label} by Rank")
    add_dataframe(ws, by_rank, "RankingByRank")

    monthly_list = monthly_list.rename(columns={"Rating": score_header})
    ws = wb.create_sheet("Monthly Splits-List")
    add_dataframe(ws, monthly_list, "MonthlySplitsList")

    ws = wb.create_sheet("Monthly Splits-Grid")
    add_dataframe(ws, monthly_grid)

    for sheet in wb.worksheets:
        style_sheet(sheet)
    for sheet_name in (f"{method.sheet_label} by Name", f"{method.sheet_label} by Rank", "Monthly Splits-List", "Monthly Splits-Grid"):
        sheet = wb[sheet_name]
        for row in sheet.iter_rows(min_row=2):
            for cell in row:
                if cell.column > 1 and isinstance(cell.value, float):
                    cell.number_format = "0.0000"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    wb.save(output_path)


def require_files(paths: list[Path]) -> None:
    missing = [path for path in paths if not path.exists()]
    if missing:
        formatted = "\n".join(f"  - {path.relative_to(ROOT)}" for path in missing)
        raise SystemExit(f"Missing build output(s):\n{formatted}\nRun `python build_dashboard.py` first.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=ROOT / "output/public_rankings",
        help="Destination directory (default: output/public_rankings)",
    )
    args = parser.parse_args()

    required = [CALCULATION_CSV, JPAR_RESULTS_CSV, EXTERNAL_LEADERBOARD_CSV, EXTERNAL_HISTORY_CSV]
    require_files(required)

    calculation = pd.read_csv(CALCULATION_CSV, low_memory=False, dtype={"event_id": "string"})
    jpar_results = pd.read_csv(JPAR_RESULTS_CSV, low_memory=False, dtype={"event_id": "string", "resolved_member_id": "string"})
    leaderboard = pd.read_csv(EXTERNAL_LEADERBOARD_CSV, low_memory=False, dtype={"member_key": "string"})
    history = pd.read_csv(EXTERNAL_HISTORY_CSV, low_memory=False, dtype={"event_id": "string", "member_key": "string"})

    qualified = make_qualified_events_df(calculation)
    event_times = make_event_time_records_df(jpar_results)

    written: list[Path] = []
    for method in METHODS:
        if method.key == "jpar":
            latest, updates, score_col, event_col = jpar_data(jpar_results)
        else:
            latest, updates, score_col, event_col = external_data(leaderboard, history, method.key)
        ranked = ranked_frame(latest, score_col, event_col, method.higher_is_better)
        names = ranked[["member_key", "Name"]].rename(columns={"Name": "full_name"})
        monthly_list, monthly_grid = monthly_frames(updates, score_col, names)
        destination = args.output_dir.resolve() / method.filename
        build_workbook(method, ranked, monthly_list, monthly_grid, qualified, event_times, destination)
        written.append(destination)

    print("Created:")
    for path in written:
        print(f"  {path}")


if __name__ == "__main__":
    main()
